export default [
  {
    first_paragraphe: [
      {
        id: 1,
        link: 'https://www.pierro-astro.com/materiel-astronomique/lunettes-astronomiques/lunettes-achromatiques-1/lunette-70-700-sur-monture-az2-sky-watcher_detail',
        img: 'https://www.maison-astronomie.com/12466-home_default/lunette-70700-sky-watcher-sur-monture-azimutale-az2.jpg',
        name: 'LUNETTE 70/700 SKY-WATCHER - 119€',
      },
      {
        id: 2,
        link: 'https://www.pierro-astro.com/materiel-astronomique/debutants/t%C3%A9lescope-dobson-mini-bresser-130mm_detail',
        img: 'https://www.maison-astronomie.com/8696-large_default/telescope-dobson-bresser-messier-5-130650.jpg',
        name: 'DOBSON BRESSER MESSIER 5" 130/650 - 215€',
      },
      {
        id: 3,
        link: 'https://www.maison-astronomie.com/fr/initiation-enfants/5756-telescope-dobson-102640-omegon.html',
        img: 'https://www.maison-astronomie.com/15614-large_default/telescope-dobson-102640-omegon.jpg',
        name: 'DOBSON 102/640 OMEGON - 249€',
      },
      {
        id: 4,
        link: 'https://www.maison-astronomie.com/fr/initiation-adultes/5645-dobson-flextube-heritage-150750-sky-watcher-3664055000513.html',
        img: 'https://www.maison-astronomie.com/15110-large_default/dobson-flextube-heritage-150750-sky-watcher.jpg',
        name: 'DOBSON 150/750 SKY-WATCHER - 260€',
      },
      {
        id: 5,
        link: 'https://www.pierro-astro.com/materiel-astronomique/marques/skywatcher/telescopes-newton/t%C3%A9lescope-newton-130-650-sur-monture-%C3%A9quatoriale-starquest-sky-watcher_detail',
        img: 'https://www.promo-optique.com/105868-large_default/telescope-130650-sur-monture-starquest-skywatcher.jpg',
        name: 'NEWTON 130/650 StARQUEST - 250€',
      },
      {
        id: 6,
        link: 'https://www.promo-optique.com/fr/telescope-debutant/52751-telescope-newton-perl-bellatrix-150-750-eq3-2-motorisable',
        img: 'https://www.promo-optique.com/9957-large_default/telescope-newton-perl-bellatrix-150-750-eq3-2-motorisable.jpg',
        name: 'NEWTON 150/750 EQ3 - 429€',
      },
    ],
    second_paragraphe: [
      {
        id: 1,
        link: 'https://www.maison-astronomie.com/fr/oculaires/5585-2005-oculaire-vixen-npl-coulant-3175mm.html#/8-focale-4_mm',
        img: 'https://www.maison-astronomie.com/14959-large_default/oculaire-vixen-npl-coulant-3175mm.jpg',
        name: 'OCULAIRE VIXEN NPL COULANT 31,75MM - 42€',
      },
      {
        id: 2,
        link: 'https://www.maison-astronomie.com/fr/oculaires/4478-1566-oculaires-explore-scientific-ler-52-argon.html#/7-focale-3_mm',
        img: 'https://www.maison-astronomie.com/8496-large_default/oculaires-explore-scientific-ler-52-argon.jpg',
        name: 'OCULAIRES EXPLORE SCIENTIFIC LER 52° ARGON - 75€',
      },
      {
        id: 3,
        link: 'https://www.maison-astronomie.com/fr/oculaires/2850-566-oculaires-takahashi-le.html#/9-focale-5_mm',
        img: 'https://www.maison-astronomie.com/5342-large_default/oculaires-takahashi-le.jpg',
        name: 'OCULAIRES TAKAHASHI LE - 234€',
      },
      {
        id: 4,
        link: 'https://www.maison-astronomie.com/fr/oculaires/2141-6-oculaires-baader-hyperion.html#/9-focale-5_mm',
        img: 'https://www.maison-astronomie.com/4994-large_default/oculaires-baader-hyperion.jpg',
        name: 'OCULAIRES BAADER HYPERION - 145€',
      },
      {
        id: 5,
        link: 'https://www.maison-astronomie.com/fr/barlow/4914-barlow-2x-kepler-o-3175mm.html',
        img: 'https://www.maison-astronomie.com/10762-large_default/barlow-2x-kepler-o-3175mm.jpg',
        name: 'BARLOW 2X KEPLER Ø 31,75MM - 38€',
      },
      {
        id: 6,
        link: 'https://www.maison-astronomie.com/fr/barlow/810-barlow-3175-mm-2x-x-cel-lx-celestron-0050234935296.html',
        img: 'https://www.maison-astronomie.com/9705-large_default/barlow-3175-mm-2x-x-cel-lx-celestron.jpg',
        name: 'BARLOW 31,75 MM 2X X-CEL LX CELESTRON - 99€',
      },
      {
        id: 7,
        link: 'https://www.maison-astronomie.com/fr/barlow/69-lentille-de-barlow-x2-tele-vue-o-3175-mm.html',
        img: 'https://www.maison-astronomie.com/6860-large_default/lentille-de-barlow-x2-tele-vue-o-3175-mm.jpg',
        name: 'LENTILLE DE BARLOW X2 TELE VUE - Ø 31,75 MM - 130€',
      },
      {
        id: 8,
        link: 'https://www.maison-astronomie.com/fr/renvois-coudes/731-renvoi-coude-en-3175-3664055002388.html',
        img: 'https://www.maison-astronomie.com/12110-large_default/renvoi-coude-en-3175.jpg',
        name: 'RENVOI COUDÉ EN 31.75 - 40€',
      },
      {
        id: 9,
        link: 'https://www.maison-astronomie.com/fr/renvois-coudes/4507-renvoi-coude-a-miroir-tele-vue-o-3175-mm.html',
        img: 'https://www.maison-astronomie.com/8587-large_default/renvoi-coude-a-miroir-tele-vue-o-3175-mm.jpg',
        name: 'RENVOI COUDÉ À MIROIR TELE VUE Ø 31,75 MM - 160€',
      },
      {
        id: 10,
        link: 'https://www.maison-astronomie.com/fr/accessoiresoptiques/911-correcteurreducteur-sc-fd-63-celestron-0050234941754.html',
        img: 'https://www.maison-astronomie.com/14076-large_default/correcteurreducteur-sc-fd-63-celestron.jpg',
        name: 'CORR/RÉDUCTEUR SC F/D 6,3 CELESTRON - 149€',
      },
      {
        id: 11,
        link: 'https://www.maison-astronomie.com/fr/accessoiresoptiques/4317-correcteur-de-coma-newton-mpcc-mark-iii-baader.html',
        img: 'https://www.maison-astronomie.com/8068-large_default/correcteur-de-coma-newton-mpcc-mark-iii-baader.jpg',
        name: 'CORRECTEUR DE COMA NEWTON MPCC MARK III BAADER - 160€',
      },
    ],
    third_paragraphe: [
      {
        id: 1,
        link: 'https://www.maison-astronomie.com/fr/telescopes-newton/2571-telescope-2001000-neq5-perl-bellatrix.html',
        img: 'https://www.maison-astronomie.com/3933-large_default/telescope-2001000-neq5-perl-bellatrix.jpg',
        name: ' TÉLESCOPE 200/1000 NEQ5 PERL BELLATRIX - 695€',
      },
      {
        id: 2,
        link: 'https://www.maison-astronomie.com/fr/telescopes-newton/5219-telescope-sky-watcher-2001000-dual-speed-sur-neq5-pro-go-to-bd-3664055000254.html',
        img: 'https://www.maison-astronomie.com/12522-large_default/telescope-sky-watcher-2001000-dual-speed-sur-neq5-pro-go-to-bd.jpg',
        name: 'TÉLESCOPE SKY-WATCHER 200/1000 DUAL SPEED SUR NEQ5 PRO GO-TO BD - 1134€',
      },
      {
        id: 3,
        link: 'https://www.maison-astronomie.com/fr/telescopes-newton/5618-telescope-sky-watcher-2001000-dual-speed-sur-eq6-r-pro-go-to-bd.html',
        img: 'https://www.maison-astronomie.com/15050-large_default/telescope-sky-watcher-2001000-dual-speed-sur-eq6-r-pro-go-to-bd.jpg',
        name: 'TÉLESCOPE SKY-WATCHER 200/1000 DUAL SPEED SUR EQ6-R PRO GO-TO BD - 1933€',
      },
      {
        id: 4,
        link: 'https://www.maison-astronomie.com/fr/lunettes-apoed/582-lunette-astronomique-sky-watcher-80ed-tube-optique-3664055000988.html',
        img: 'https://www.maison-astronomie.com/12403-large_default/lunette-astronomique-sky-watcher-80ed-tube-optique.jpg',
        name: 'LUNETTE ASTRONOMIQUE SKY-WATCHER 80ED (TUBE OPTIQUE) - 497€',
      },
      {
        id: 5,
        link: 'https://www.maison-astronomie.com/fr/lunettes-apoed/1010-lunette-sky-watcher-esprit-80ed-3664055001046.html',
        img: 'https://www.maison-astronomie.com/12393-large_default/lunette-sky-watcher-esprit-80ed.jpg',
        name: 'LUNETTE SKY-WATCHER ESPRIT 80ED - 1490€',
      },
      {
        id: 6,
        link: 'https://www.maison-astronomie.com/fr/lunettes-apoed/2527-lunette-sky-watcher-esprit-100ed-3664055001053.html',
        img: 'https://www.maison-astronomie.com/12392-large_default/lunette-sky-watcher-esprit-100ed.jpg',
        name: 'LUNETTE SKY-WATCHER ESPRIT 100ED - 2244€',
      },
      {
        id: 7,
        link: 'https://www.maison-astronomie.com/fr/telescopes-compacts/930-630-tube-optique-seul-sc-800-fastar-celestron-8.html#/341-version_opt_monture_moteurs-platine_standard_vixen_sky_watcher',
        img: 'https://www.maison-astronomie.com/9917-large_default/tube-optique-seul-sc-800-fastar-celestron-8.jpg',
        name: 'TUBE OPTIQUE SEUL SC 800 FASTAR CELESTRON 8 - 1199€',
      },
      {
        id: 8,
        link: 'https://www.maison-astronomie.com/fr/telescopes-compacts/931-629-tube-optique-seul-sc-925-fastar-celestron-925.html#/342-version_opt_monture_moteurs-platine_large_losmandy_cge',
        img: 'https://www.maison-astronomie.com/9922-large_default/tube-optique-seul-sc-925-fastar-celestron-925.jpg',
        name: 'TUBE OPTIQUE SEUL SC 925 FASTAR CELESTRON 9.25 - 1764€',
      },
      {
        id: 9,
        link: 'https://www.maison-astronomie.com/fr/telescopes-compacts/1290-tube-optique-seul-sc-925-edgehd-celestron-0050234104098.html',
        img: 'https://www.maison-astronomie.com/9866-large_default/tube-optique-seul-sc-925-edgehd-celestron.jpg',
        name: 'TUBE OPTIQUE SEUL SC 925 EDGEHD CELESTRON - 3115€',
      },
      {
        id: 10,
        link: 'https://www.maison-astronomie.com/fr/telescopes-compacts/1291-tube-optique-seul-sc-1100-edgehd-celestron-0050234105095.html',
        img: 'https://www.maison-astronomie.com/9871-large_default/tube-optique-seul-sc-1100-edgehd-celestron.jpg',
        name: 'TUBE OPTIQUE SEUL SC 1100 EDGEHD CELESTRON - 4365€',
      },
    ],
  },
];
