module.exports = {
    INTERNAL_ERROR: "Internal server error, please retry in a few minutes",
    CONTENT_NOT_FOUND: "The requested content was not found or was moved",
    USER_NOT_FOUND: "User not found",
    EXPLORATION_NOT_FOUND: "Exploration not found",
    MISSING_CREDENTIALS: "Missing credentials",
    EMAIL_NOT_FOUND: "This email or username does not exist",
    PASSWORD_NOT_MATCH: "Password does not match",
    USER_ALREADY_EXISTS: "Username already exists",
    EMAIL_ALREADY_EXISTS: "Email already exists",
    INVALID_TOKEN: "Invalid token",
    MISSING_TOKEN: "You must provide a token",
    TOKEN_AUTH_FAILED: "Failed to authenticate token.",
    UNAUTHORIZED: "You are not authorized to perform this action",
    MISSING_EXPLORATION_NAME: "Please provide an exploration name",
    EXPLORATION_LIMIT_REACHED: "You have reached the maximum number of explorations allowed",
    PASSWORD_TOO_SHORT: "The password must be at least 8 characters long",
    PASSWORD_UPDATED: "Password updated. Please login again",
    USERNAME_UPDATED: "Username updated.",
    ALREADY_FOLLOWING_USER: "You are already following this user",
    FOLLOW_IS_SUCCESS: "You are now following this user",
    UNFOLLOW_IS_SUCCESS: "You are no longer following this user",
    USER_NOT_FOLLOWING: "You are not following this user",
    EXPLORATION_PARTICIPANTS_LIMIT_REACHED: "You have reached the maximum number of users allowed in an exploration",
    USER_ALREADY_PARTICIPATE: "You are already participating in this exploration",
    USER_NOT_PARTICIPATE: "You are not participating in this exploration",
    SUBSCRIBE_SUCCESS: "You have successfully subscribed to this exploration",
    UNSUBCRIBE_SUCCESS: "You have successfully unsubscribed from this exploration",
    COMMENT_ADDED: "Comment added successfully",
    COMMENT_EDITED: "Comment edited successfully",
    COMMENT_NOT_FOUND: "Comment not found",
}