module.exports = {
    INTERNAL_ERROR: "Internal server error, please retry in a few minutes",
    CONTENT_NOT_FOUND: "The requested content was not found or was moved",
    USER_NOT_FOUND: "User not found",
    EXPLORATION_NOT_FOUND: "Exploration not found",
    MISSING_CREDENTIALS: "Missing credentials",
    EMAIL_NOT_FOUND: "This email or username does not exist",
    PASSWORD_NOT_MATCH: "Password does not match",
    USER_ALREADY_EXISTS: "Username already exists",
    EMAIL_ALREADY_EXISTS: "Email already exists",
    INVALID_TOKEN: "Invalid token",
    MISSING_TOKEN: "You must provide a token",
    TOKEN_AUTH_FAILED: "Failed to authenticate token.",
    UNAUTHORIZED: "You are not authorized to perform this action",
    MISSING_EXPLORATION_NAME: "Please provide an exploration name",
    EXPLORATION_LIMIT_REACHED: "You have reached the maximum number of explorations allowed",
    PASSWORD_TOO_SHORT: "The password must be at least 8 characters long",
    PASSWORD_UPDATED: "Password updated. Please login again",
    USERNAME_UPDATED: "Username updated."
}